// Do not edit this file; automatically generated by build.py.
'use strict';

var reg=/^#([0-9a-fA-f]{3}|[0-9a-fA-f]{6})$/;String.prototype.colorRgb=function(){var b=this.toLowerCase();if(b&&reg.test(b)){if(4===b.length){for(var c="#",a=1;4>a;a+=1)c+=b.slice(a,a+1).concat(b.slice(a,a+1));b=c}c=[];for(a=1;7>a;a+=2)c.push(parseInt("0x"+b.slice(a,a+2)));return c.join(".")}return b};